# Generated by Django 5.2.3 on 2025-06-20 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre técnico de la app (ej: 'iatp', 'users')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Nombre que se muestra al usuario', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción de la funcionalidad de la app')),
                ('icon', models.CharField(default='fas fa-cube', help_text='Clase CSS del icono (Font Awesome)', max_length=50)),
                ('app_type', models.CharField(choices=[('admin', 'Administrativa'), ('saas', 'Micro SAAS')], help_text='Tipo de aplicación', max_length=20)),
                ('url_name', models.CharField(help_text="Nombre de la URL para acceder (ej: 'iatp:teapot')", max_length=100)),
                ('color', models.CharField(default='forge-blue', help_text='Color del tema de la app', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Si la app está disponible para uso')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aplicación Registrada',
                'verbose_name_plural': 'Aplicaciones Registradas',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AppUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='app.appregistry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Uso de App',
                'verbose_name_plural': 'Logs de Uso de Apps',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAppAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del acceso (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si el acceso está activo')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el acceso otorgado')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='app.appregistry')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Usuario que otorgó el acceso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a Aplicación',
                'verbose_name_plural': 'Accesos a Aplicaciones',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'app')},
            },
        ),
    ]
